FROM golang:1.27-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o demo ./cmd/demo_server

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /build/demo .
EXPOSE 3000
ENTRYPOINT ["./demo"]